# Generated by Django 3.2.18 on 2024-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
